#!/bin/sh
# SPDX-License-Identifier: Unlicense

echo "Building for linux amd64..."
GOOS=linux GOARCH=amd64 go build -o kwinit-linux-amd64
echo "Building for linux arm64..."
GOOS=linux GOARCH=arm64 go build -o kwinit-linux-arm64
echo "Building for windows amd64..."
GOOS=windows GOARCH=amd64 go build -o kwinit-windows-amd64.exe
echo "Building for windows arm64..."
GOOS=windows GOARCH=arm64 go build -o kwinit-windows-arm64.exe
echo "Building for darwin amd64..."
GOOS=darwin GOARCH=amd64 go build -o kwinit-darwin-amd64
echo "Building for darwin arm64..."
GOOS=darwin GOARCH=arm64 go build -o kwinit-darwin-arm64
